spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/blog

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    output:
      ansi:
        enabled: always
    devtools:
      restart:
        enabled: true
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
